const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const stream = require('stream');

router.post('/', (req, res) => {
  const { name, subject, score, grade, date, generatedOn } = req.body;

  if (!name || !subject || !score || !grade || !date || !generatedOn) {
    return res.status(400).json({ error: 'Missing fields in request body' });
  }

  const doc = new PDFDocument();
  const bufferStream = new stream.PassThrough();

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=${subject}-report.pdf`);

  doc.pipe(bufferStream);

  // PDF content
  doc.fontSize(20).text('CourseHub Assessment Report', { align: 'center' });
  doc.moveDown();
  doc.fontSize(14).text(`Name: ${name}`);
  doc.text(`Subject: ${subject}`);
  doc.text(`Score: ${score}`);
  doc.text(`Grade: ${grade}`);
  doc.text(`Date: ${date}`);
  doc.moveDown();
  doc.fontSize(10).text(`Generated by CourseHub • ${generatedOn}`);

  doc.end();

  bufferStream.pipe(res);
});

module.exports = router;
